[package]
name = "rust_onnx_nlp"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
tokenizers = "0.13.3"
tract-onnx = "0.20.4"
actix-web = "4"
serde = "1.0.163"

[[bin]]
name = "inference_api"
